### ISSUE TITLE
Support Scrobbling played tracks using the Simple last.FM Scrobbler

### ISSUE THREAD

**Issue by JonTheNiceGuy** [telecapoland/jamendo-android#2]
I use this app to search for tracks to play in my podcast, but I don't always remember what I've played. It would be useful to scrobble my jamendo listening history.

**Comment by lidel** [comment]
Indeed, it would be great to get Jamendo app scrobbling with Simple last.FM Scrobbler!

This issue is also [reported for Simple last.FM Scrobbler](https://code.google.com/p/a-simple-lastfm-scrobbler/issues/detail?id=39), but I think it would be  easier to get Jamendo app to respect one of well-established scrobbling APIs that  Simple last.FM Scrobbler already supports.

**Comment by MarcinGil** [comment]
We added this to our todo feature list.

**Comment by MarcinGil** [comment]
We are currently testing support for SLS so expect a new release soon!

**Comment by lidel** [comment]
Great! :-)

**Comment by lidel** [comment]
Just tested a new version from the Android Market. 
Scrobbling works great. Thanks!

**Comment by MarcinGil** [comment]
Thanks! Glad to hear you like it!
